CREATE TABLE products (
    product_id		NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1000 INCREMENT BY 1 PRIMARY KEY,
    name     	VARCHAR2(50),
    category	VARCHAR2(50),
    price	NUMBER(*,2),
    discount    NUMBER(*,2),
    description LONG
);